# Site settings
title: Spudmux 
email: info@spudmux.com
description: "A collection of things picked up over time" # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spudmux.com" # the base hostname & protocol for your site
twitter_username: spudmux 
github_username: spudmux 

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    use_coderay: true 
    coderay:
        coderay_line_numbers: table
        coderay_css: style

# Exclude 
exclude: [Rakefile]
