# Site settings
title: spudmux 
email: info@spudmux.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spudmux.com" # the base hostname & protocol for your site
twitter_username: spudmux 
github_username: spudmux 

# Build settings
markdown: kramdown
