# Site settings
title: Spudmux 
email: info@spudmux.com
description: "A collection of things picked up over time" # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spudmux.com" # the base hostname & protocol for your site
twitter_username: spudmux 
github_username: spudmux 

# Build settings
sass:
  sass_dir: css
markdown: kramdown
excerpt_separator: <!--more-->
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
# Exclude 
exclude:
  - Rakefile
  - _todo.md
  - .idea
